29 ekran logowania
HakierGrzonzo/Kronikarz pull request #43
Opened 2022-12-04 22:05 UTC by Havystar

# Co zostało zrobione:

- Dodanie loga i loga bez tła
- stworzenie fav icon
- wygenerowanie clienta 
- połączenie z backendem logowania
- dodanie sprawdzenia czy faktycznie jesteś zalogowany 
- update gitignora i configów
- zmiana domyślnego thema
- dodanie wstępnego layoutu dla strony

# Na co należy zwrócić uwagę:

- czy stosuje się do zasad remixa
- optymalizacja
- czy coś trzeba wydzielić do utilsów

2022-12-05 16:20 UTC, HakierGrzonzo requested changes
Maybe let's clean it up a bit and extract stuff like our appbar to separate components?

2022-12-05 16:22 UTC, HakierGrzonzo commented
@Havystar Może dodaj openapi do gitignore, bo zaśmieca to diffy

2022-12-06 20:29 UTC, Havystar commented on frontend/app/routes/login.tsx
> +          backgroundColor: "#e0edf2",
We have other backgroundColor in mui. This is only for this img to fill blank page with same color.

2022-12-07 11:32 UTC, Havystar commented
> Maybe let's clean it up a bit and extract stuff like our appbar to separate components?

Will be done in #14

2022-12-14 19:14 UTC, HakierGrzonzo approved these changes
I removed the openapi client from frontend

2022-12-14 19:15 UTC, merged